name: Deploy Vue to EC2 (manual)

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'deploy or restart'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - restart

jobs:
  build:
    if: ${{ github.event.inputs.command == 'deploy' }} # ← 仅在 deploy 时构建
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: build docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/vue-deploy .
      - name: push to dockerhub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vue-deploy:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull the docker image
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/vue-deploy:latest
      - name: run docker container
        run: |
          if [ "${{ github.event.inputs.command }}" = "deploy" ]; then
            docker stop vue-deploy || true
            docker rm vue-deploy || true
            docker run -d --name vue-deploy -p 4173:4173 ${{ secrets.DOCKER_HUB_USERNAME }}/vue-deploy:latest
          elif [ "${{ github.event.inputs.command }}" = "restart" ]; then
            docker restart vue-deploy || true
          else
            echo "Unknown command: ${{ github.event.inputs.command }}"
            exit 1
          fi